### ISSUE TITLE
Does not seem to work

### ISSUE THREAD

**Issue by nikolay12** [developersteve/ruby-braintree-hosted-fields#1]
I followed the instructions but couldn't make it work:

localhost:ruby-braintree-hosted-fields nnikolo$ ruby app.rb
/Users/nnikolo/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- awesome_print (LoadError)
    from /Users/nnikolo/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from app.rb:3:in `<main>'

**Comment by nikolay12** [comment]
It was just missing a gem - I added it in the fork.
